### ISSUE TITLE
Hippybot is broken under Python 2.7.9

### ISSUE THREAD

**Issue by vmalloc** [1stvamp/hippybot#18]
When attempting to run I get:

```
Traceback (most recent call last):
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/hippybot/bot.py", line 256, in run
    bot = HippyBot(self.config._sections)
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/hippybot/bot.py", line 61, in __init__
    self.join_room(channel, config['connection']['nickname'])
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/hippybot/bot.py", line 166, in join_room
    self.connect().send(pres)
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/jabberbot.py", line 208, in connect
    conres = conn.connect()
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/xmpp/client.py", line 205, in connect
    while not self.TLS.starttls and self.Process(1): pass
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/xmpp/transports.py", line 337, in StartTLSHandler
    self._startSSL()
  File ".../src/work/infrabot/.env/lib/python2.7/site-packages/xmpp/transports.py", line 316, in _startSSL
    tcpsock._sslIssuer = tcpsock._sslObj.issuer()
AttributeError: '_ssl._SSLSocket' object has no attribute 'issuer'
```

**Comment by 1stvamp** [comment]
@vmalloc thanks for this and sorry for the late response, seems I'm still not getting notifications for this repo off GH, doh.

**Comment by jimlerza** [comment]
This is actually a bug in xmlpppy. I was able to get hippybot working on Python 2.7.9 by replacing  xmlpppy with [ArchipelProject/xmpppy](https://github.com/ArchipelProject/xmpppy).
